apiVersion: 1

datasources:
  - name: Elastic
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    jsonData:
      index: '[app-logs-]YYYY.MM.DD'
      interval: Daily
      timeField: '@timestamp'