{
 "title": "back_requests",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Raw logs",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Logs cnt by level within 5 min window",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "level.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Avg duration (ms) by endpoint",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uri.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "duration (ms)", "id": "1", "type": "avg" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "success/error requests ratio",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "level.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "500" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "message:\"Request responded\" AND status:\"200\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "fail",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "message:\"Request responded\" AND NOT status:\"200\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}